name: CI Node.js

on: [push, pull_request]

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v4

      - name: Installer les dépendances
        run: npm install

      - name: Lancer les tests
        run: npm test
